---
- hosts: all
  become: true

  tasks:
  - name: create docker image using war file
    command: "docker build -t simple-devops-image:latest ."
    args:
      chdir: /opt/docker

  - name: create tag to a image
    command: docker tag simple-devops-image manmohanmirkar/simple-devops-image

  - name: push image to docker hub
    command: docker push manmohanmirkar/simple-devops-image

  - name: remove docker image
    command: docker rmi simple-devops-image:latest manmohanmirkar/simple-devops-image
    ignore_errors: yes
